create table if not exists languages (
  id bigint primary key,
  name text not null unique,
  description text not null default ''
);

create table if not exists courses (
  id bigint primary key,
  language_id bigint not null references languages(id) on delete restrict,
  title text not null,
  level text not null check (level in ('Beginner', 'Intermediate', 'Advanced')),
  duration_weeks integer not null check (duration_weeks > 0),
  description text not null default '',
  image_url text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists lessons (
  id bigint primary key,
  course_id bigint not null references courses(id) on delete cascade,
  title text not null,
  summary text not null default '',
  lesson_order integer not null check (lesson_order > 0),
  key_phrases jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (course_id, lesson_order)
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  course_id bigint not null references courses(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  unique (student_id, course_id)
);

create table if not exists lesson_progress (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references enrollments(id) on delete cascade,
  lesson_id bigint not null references lessons(id) on delete cascade,
  is_completed boolean not null default false,
  completed_at timestamptz,
  unique (enrollment_id, lesson_id)
);

create table if not exists users (
  id text primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id text primary key,
  title text not null,
  message text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists gallery_photos (
  id text primary key,
  title text not null,
  image_url text not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists site_settings (
  setting_key text primary key,
  setting_value text not null default '',
  updated_at timestamptz not null default now()
);

alter table if exists students add column if not exists phone text not null default '';

create index if not exists idx_languages_name on languages (name);
create index if not exists idx_courses_language on courses (language_id);
create index if not exists idx_lessons_course on lessons (course_id);
create index if not exists idx_students_email on students (email);
create index if not exists idx_enrollments_student on enrollments (student_id);
create index if not exists idx_enrollments_course on enrollments (course_id);
create index if not exists idx_lesson_progress_enrollment on lesson_progress (enrollment_id);
create index if not exists idx_lesson_progress_lesson on lesson_progress (lesson_id);
create index if not exists idx_users_email on users (email);
create index if not exists idx_notifications_created_at on notifications (created_at desc);
create index if not exists idx_gallery_position on gallery_photos (position asc, created_at desc);
create index if not exists idx_site_settings_updated_at on site_settings (updated_at desc);
